2017-08-10 16:38:56,484 logger.py[line:41] INFO 500《记忆大师》......《森山中教习所》等500部电影数据插入数据库完毕
2017-08-10 16:39:00,803 logger.py[line:41] INFO 1000《因为爱》......《我在伊朗长大》等500部电影数据插入数据库完毕
2017-08-10 16:39:05,118 logger.py[line:41] INFO 1500《不能说的秘密》......《博学无术》等500部电影数据插入数据库完毕
2017-08-10 16:39:09,546 logger.py[line:41] INFO 2000《W的悲剧》......《锦衣卫》等500部电影数据插入数据库完毕
2017-08-10 16:39:13,650 logger.py[line:41] INFO 2500《武侠》......《幸福》等500部电影数据插入数据库完毕
2017-08-10 16:39:17,562 logger.py[line:41] INFO 3000《绿鱼》......《龙虎门》等500部电影数据插入数据库完毕
2017-08-10 16:39:21,521 logger.py[line:41] INFO 3500《功夫梦》......《苦月亮》等500部电影数据插入数据库完毕
2017-08-10 16:39:25,618 logger.py[line:41] INFO 4000《隐婚男女》......《地狱医院》等500部电影数据插入数据库完毕
2017-08-10 16:39:29,586 logger.py[line:41] INFO 4500《神秘村》......《逃亡僵尸岛》等500部电影数据插入数据库完毕
2017-08-10 16:39:32,788 logger.py[line:41] INFO 4571《鬼三惊2》......《守护者联盟》等71部电影数据插入数据库完毕
2017-08-10 16:39:32,789 logger.py[line:41] INFO 全部电影数据转存数据库完毕，共计：4571条
2017-08-18 18:23:10,178 logger.py[line:41] INFO 1000《记忆大师》......《我在伊朗长大》等1000部电影数据插入数据库完毕
2017-08-18 18:23:10,865 logger.py[line:50] ERROR 数据转存数据库失败。失败的起始电影：2124724 不能说的秘密
Traceback (most recent call last):
  File "db.py", line 69, in <module>
    db.insert_movie(infos)
  File "db.py", line 44, in insert_movie
    self.__insert_many(sql, params)
  File "db.py", line 38, in __insert_many
    self.cursor.executemany(sql, params)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 195, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 195, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 164, in execute
    query = self.mogrify(query, args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
2017-08-18 18:27:43,239 logger.py[line:41] INFO 500《记忆大师》......《森山中教习所》等500部电影数据插入数据库完毕
2017-08-18 18:27:47,576 logger.py[line:41] INFO 1000《因为爱》......《我在伊朗长大》等500部电影数据插入数据库完毕
2017-08-18 18:27:48,202 logger.py[line:50] ERROR 数据转存数据库失败。失败的起始电影：2124724 不能说的秘密
Traceback (most recent call last):
  File "db.py", line 70, in <module>
    db.insert_movie(infos)
  File "db.py", line 45, in insert_movie
    self.__insert_many(sql, params)
  File "db.py", line 39, in __insert_many
    self.cursor.executemany(sql, params)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 195, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 195, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 164, in execute
    query = self.mogrify(query, args)
  File "D:\Codebase\Python\proj\douban-movie-visualization\venv\lib\site-packages\pymysql\cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
